"""
Architectural prompt generator — white-label packs for users to host
client-facing programs *without* calling an external LLM.

Deterministic templates filled from circle-system state + Super Program families.
"""

from __future__ import annotations

from typing import Any


SYSTEM_TEMPLATE = """# {product_name} — Architectural Runtime Prompt (offline)
# Generated by Metrix Circle-System · no external LLM required

## Role
You are a deterministic operator for {product_name} serving client: {client_label}.
You do NOT invent certainty. You only use statuses: CERTAIN YES / CERTAIN NO / UNDEFINED.

## Super Program subset
{super_block}

## Circle layers (needs)
{layers_block}

## Parameter map
{params_block}

## Terminal functions available
{terminals_block}

## Rules
1. If status is UNDEFINED → emit Super-Speed test questions (quiz form), analyze ASSEMBLY not heat.
2. Answer tone uses linguistic warmth band: {warmth_band} — warmth never overrides truth.
3. Tech write is inserted only via phased ops rules.
4. Pilot gate: assembly_score >= 0.45 AND consistency >= 0.62.
5. Support: forward anomalies from metric firmware (SFI/ASM/CNS/PAP).
6. Human-authorized: branding/VA and client signer must approve identity and acceptance.

## Output formats
- consult_json
- tech_write_markdown
- pilot_charter
- support_ticket
- white_label_prompt (this document)

## Offline execution
All decisions are rule/table driven. Do not call external LLM APIs.
"""


MODULE_PROMPT_TEMPLATE = """## Module prompt: {module_id}
Input slots: {slots}
Process:
{steps}
Output schema: {outputs}
Warmth: apply only on final natural-language strings.
"""


class ArchitecturalPromptGenerator:
    """Generate offline architectural prompts for white-label deployment."""

    name = "Architectural Prompt Generator (no external LLM)"

    def run(
        self,
        *,
        certainty_result: dict[str, Any] | None = None,
        super_program: dict[str, Any] | None = None,
        layers_result: dict[str, Any] | None = None,
        terminal_specs: dict[str, Any] | None = None,
        warmth: dict[str, Any] | None = None,
        product_name: str = "Client Metrix Runtime",
        client_label: str = "end_client",
    ) -> dict[str, Any]:
        certainty_result = certainty_result or {}
        super_program = super_program or {}
        layers_result = layers_result or {}
        terminal_specs = terminal_specs or {}
        warmth = warmth or {"band": "neutral"}

        params = certainty_result.get("parameters") or []
        params_block = "\n".join(
            f"- {p.get('slot')}: {p.get('status')} · {str(p.get('snippet') or '')[:100]}"
            for p in params
        ) or "- (empty — run certainty analyzer first)"

        best = super_program.get("best_subset") or []
        super_block = "\n".join(
            f"- {b.get('excel_name')} (fit={b.get('fit')}): {b.get('role')}" for b in best
        ) or "- (no match yet)"

        layers_block = "\n".join(
            f"- {L.get('layer')}: {L.get('need_level')} ({L.get('need_strength')})"
            for L in layers_result.get("layers") or []
        ) or "- (no layers)"

        terminals_block = "\n".join(
            f"- {t.get('id')}: {t.get('title')} [{t.get('status')}]"
            for t in terminal_specs.get("terminal_functions") or []
        ) or "- tech_write_core, pilot_charter"

        system_prompt = SYSTEM_TEMPLATE.format(
            product_name=product_name,
            client_label=client_label,
            super_block=super_block,
            layers_block=layers_block,
            params_block=params_block,
            terminals_block=terminals_block,
            warmth_band=warmth.get("band") or "neutral",
        )

        module_prompts = []
        for mid, slots, steps, outputs in (
            (
                "certainty_pass",
                "raw_text",
                "1. extract params\n2. indirect CY/CN/U",
                "{parameters, buckets}",
            ),
            (
                "super_speed_tests",
                "uncertain_params",
                "1. isolate\n2. quiz questions\n3. assembly map",
                "{test_battery, items}",
            ),
            (
                "tech_write",
                "confirmed_layers + super_program",
                "1. terminal specs\n2. phased insert",
                "{markdown_specs}",
            ),
            (
                "pilot_runtime",
                "pilot_charter + metrics",
                "1. deploy slice\n2. metric firmware\n3. support",
                "{pilot_status, tickets}",
            ),
        ):
            module_prompts.append(
                MODULE_PROMPT_TEMPLATE.format(
                    module_id=mid, slots=slots, steps=steps, outputs=outputs
                )
            )

        return {
            "module": self.name,
            "branch": "white_label_arch_prompts_no_external_llm",
            "product_name": product_name,
            "client_label": client_label,
            "system_prompt": system_prompt,
            "module_prompts": module_prompts,
            "deployment_notes": [
                "Store prompts as versioned markdown/JSON next to rules tables.",
                "Runtime evaluates rules + lexicons only (deterministic).",
                "Users place this pack under their client brand without OpenAI/Anthropic/etc.",
                "Optional: human tech writer polishes markdown after system_prompt draft.",
            ],
            "files_suggested": [
                "prompts/system.md",
                "prompts/modules/*.md",
                "rules/ops_rules.json",
                "lexicon/read_write.json",
            ],
        }
